import CategoryIcon from "@/icons/layout/menu/category-icon";
import { SubMenuType } from "@/types";

const categories: SubMenuType[] = [
  {
    id: 1,
    title: "All Posts",
    slug: "/blog",
    icon: CategoryIcon,
    description: "All blog posts.",
    keywords: [
      "blog",
      "mdx",
      "next.js",
      "react",
      "tailwindcss",
      "kotlin",
      "android",
      "javascript",
      "web development",
      "programming",
      "frontend",
      "backend",
      "full stack",
      "typescript",
      "css",
      "html",
      "node.js",
      "software engineering",
      "mobile development",
    ],
  },
  {
    id: 2,
    title: "Next.js",
    slug: "/blog/category/nextjs",
    icon: CategoryIcon,
    description: "Next.js blog posts.",
    keywords: [
      "next.js",
      "react",
      "javascript",
      "web development",
      "programming",
      "frontend",
      "backend",
      "full stack",
      "typescript",
      "css",
      "html",
      "node.js",
      "software engineering",
    ],
  },
  {
    id: 3,
    title: "Android",
    slug: "/blog/category/android",
    icon: CategoryIcon,
    description: "Android blog posts.",
    keywords: [
      "android",
      "kotlin",
      "java",
      "mobile development",
      "programming",
      "frontend",
      "backend",
      "full stack",
      "typescript",
      "css",
      "html",
      "node.js",
      "software engineering",
    ],
  },
  {
    id: 4,
    title: "Tailwind CSS",
    slug: "/blog/category/tailwindcss",
    icon: CategoryIcon,
    description: "Tailwind CSS blog posts.",
    keywords: [
      "tailwindcss",
      "react",
      "javascript",
      "web development",
      "programming",
      "frontend",
      "backend",
      "full stack",
      "typescript",
      "css",
      "html",
      "node.js",
      "software engineering",
    ],
  },
  {
    id: 5,
    title: "React",
    slug: "/blog/category/react",
    icon: CategoryIcon,
    description: "React blog posts.",
    keywords: [
      "react",
      "javascript",
      "web development",
      "programming",
      "frontend",
      "backend",
      "full stack",
      "typescript",
      "css",
      "html",
      "node.js",
      "software engineering",
    ],
  },
  {
    id: 6,
    title: "Kotlin",
    slug: "/blog/category/kotlin",
    icon: CategoryIcon,
    description: "Kotlin blog posts.",
    keywords: [
      "kotlin",
      "java",
      "android",
      "mobile development",
      "programming",
      "frontend",
      "backend",
      "full stack",
      "typescript",
      "css",
      "html",
      "node.js",
      "software engineering",
    ],
  },
];

export default categories;
