import { SeoType } from "@/types";

// This file contains the core meta data for the application
const seoConfig: SeoType = {
  title: "Hi, I'm Tim",
  subTitle: "Welcome to my portfolio",
  ogImage: "/images/opengraph-image.png",
  twitterImage: "/images/twitter-image.png",
  author: {
    name: "Tim Baz",
    twitterUrl: "https://x.com/timtbdev",
    twitterAddress: "@timtbdev",
    email: "timtb.dev@gmail.com",
  },
  description: "Frontend developer in the Bay Area.",
  tags: [
    "Tumur Bazarragchaa",
    "Tim Baz",
    "frontend developer",
    "React developer",
    "Next.js developer",
    "Tailwind CSS expert",
    "shadcn/ui developer",
    "Headless UI components",
    "React UI frameworks",
    "modern frontend development",
    "responsive web design",
    "React component library",
    "Next.js full-stack development",
    "SSR and SSG with Next.js",
    "best React UI frameworks",
    "Tailwind CSS styling",
    "building modern web apps",
    "React performance optimization",
    "Next.js SEO best practices",
    "frontend developer portfolio",
    "Next.js API routes",
    "shadcn UI customization",
    "React UI/UX design",
    "server-side rendering React",
    "static site generation Next.js",
    "best UI frameworks for React",
    "frontend best practices 2025",
    "React hooks tutorial",
    "dark mode with Tailwind CSS",
    "Next.js and Tailwind CSS",
    "frontend developer roadmap",
    "React developer portfolio",
    "best frontend technologies",
    "Next.js and headless CMS",
    "React state management",
    "fast and scalable frontend apps",
    "best deployment platforms for Next.js",
    "React Tailwind templates",
    "frontend tools for developers",
    "React UI libraries 2025",
    "Next.js vs React performance",
    "modern web development stack",
    "best hosting for Next.js apps",
    "shadcn vs Radix UI",
    "React with Tailwind best practices",
    "frontend development trends",
    "Next.js vs traditional React",
    "frontend coding challenges",
    "React UI kit for developers",
    "designing accessible web apps",
    "frontend framework comparison",
    "best design systems for React",
    "Android developer",
    "Android development",
    "Android app development",
    "Android software engineer",
    "Hire Android developer",
    "Freelance Android developer",
    "Custom Android app development",
    "Android development company",
    "Android app design and development",
    "Native Android app solutions",
    "Full-stack Android development",
    "Enterprise Android development",
    "Professional Android developer for hire",
    "End-to-end Android application development services",
    "How to choose the best Android development company",
    "User-friendly Android UI/UX design and development",
    "Scalable Android apps for startups and enterprises",
    "Android app maintenance and support services",
    "Kotlin Android developer",
    "Java-based Android apps",
    "Android Jetpack libraries",
    "MVVM architecture for Android",
    "Android SDK integration",
    "Android app testing and QA",
    "E-commerce Android app development",
    "Healthcare Android application solutions",
    "On-demand services Android apps",
    "Educational Android mobile apps",
    "Fintech Android development",
    "Android developer in San-Francisco Bay Area",
    "Top Android development services in San-Francisco Bay Area",
    "Best Android app development company near me",
    "Modern Android development with Jetpack",
    "Jetpack Compose for Android",
    "Compose Material 3 (Material You) design",
    "Jetpack Navigation",
    "Android Jetpack WorkManager",
    "Jetpack Compose UI testing",
    "State management in Jetpack Compose",
    "Kotlin Coroutines",
    "Kotlin Flow",
    "Reactive programming with Kotlin",
    "Kotlin Multiplatform Mobile (KMM)",
    "Dependency injection with Hilt",
    "Android architecture components (ViewModel, LiveData, Room)",
    "MVVM architecture with Kotlin",
    "Gradle build optimization for Android",
    "Continuous Integration (CI) for Android apps",
    "Android app performance optimization",
    "Multi-module Android project architecture",
    "Automated testing for Android (Espresso, JUnit)",
    "Firebase integration for Android",
    "Google Play App Bundle",
    "Serverless backend for Android (Firebase Functions)",
    "APIs integration in Android apps",
    "Push notifications setup for Android",
    "Android Machine Learning Kit",
    "Android App Bundles and Instant Apps",
    "Android data binding vs. view binding",
    "Compose vs. XML layouts",
    "Design patterns for modern Android apps",
    "Material Design 3 best practices",
    "Advanced Android development techniques",
    "Android modularization architecture",
    "Jetpack Compose vs traditional Android UI",
    "Best practices for scalable Android apps",
    "UI/UX innovation with Android Compose",
    "Next.js for Android developers",
    "Next.js SEO optimization for mobile apps",
    "Full-stack development with Next.js and Android",
    "Next.js for mobile-friendly web applications",
    "Building mobile-first web apps with Next.js",
    "Next.js and Firebase for seamless app development",
    "Server-side rendering (SSR) with Next.js for mobile apps",
    "Next.js vs traditional frontend frameworks for Android developers",
    "Next.js static site generation (SSG) for mobile apps",
    "Best Next.js UI frameworks for Android web projects",
    "Combining Next.js and React Native for cross-platform apps",
    "Optimizing Next.js performance for mobile-first applications",
  ],
};

export default seoConfig;
